package jp.ac.kyoto_su.ise.tamadalab.bydi.translators;

import java.util.List;
import java.util.function.Consumer;
import java.util.stream.Stream;

import org.kohsuke.args4j.Argument;
import org.kohsuke.args4j.CmdLineException;
import org.kohsuke.args4j.CmdLineParser;
import org.kohsuke.args4j.Option;

public class Arguments {
    @Option(name="-t", aliases="-toolname", usage="Specify the tool name of mapping.")
    private String type;

    @Option(name="-h", aliases="--help", usage="Print this message")
    private boolean helpFlag = false;

    @Argument
    private List<String> arguments;

    public String type() {
        return type;
    }

    public Stream<String> stream() {
        return arguments.stream();
    }

    public void parse(String[] args) {
        try {
            CmdLineParser parser = new CmdLineParser(this);
            parser.parseArgument(args);
        } catch (CmdLineException e) {
            throw new InternalError(e);
        }
    }

    private void printHelp() {
        System.out.println("translator [OPTION] <<FILE_NAME>");
        System.out.println("OPTION");
        System.out.println("    -h, --help:            Print this message.");
        System.out.println("    -t, --toolname <NAME>: Specify the tool name of mapping.");
        System.out.println("ARGUMENTS");
        System.out.println("    FILE_NAME: mapping file name generated by some obfuscation tool.");
    }

    public void perform(Consumer<Arguments> action) {
        if(helpFlag)
            action.accept(this);
        else
            printHelp();
    }
}
